// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Hello
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/plain
//
// swagger:meta
package restapi
