swagger: '2.0'
info:
  title: Greeting Server
  version: '1.0'
host: api.server.test
basePath: /
schemes:
  - https
paths:
  /hello:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          type: string
          required: false
          in: query
          description: defaults to World if not given
      responses:
        '200':
          description: returns a greeting
          schema:
            type: string
            description: contains actual greeting msg